### ISSUE TITLE
Multiple PING Problem. No 

### ISSUE THREAD

**Issue by BlackHoleVR** [YandievRuslan/sx1278-LoRa-RaspberryPi#3]
Hello, I'm using your library to make a project. 
I started from the PING example on Raspberry PI4 and send a message to arduino. Arduino sent response to Raspberry.  After sending the 189 message the raspberry is no longer notified of the end of the transmission -> the TX callback function is no longer called.
Have you tried doing multiple PING? 
I attach the C main I'm using
[main.txt](https://github.com/YandievRuslan/sx1278-LoRa-RaspberryPi/files/7288650/main.txt)

**Comment by YandievRuslan** [comment]
Hello! I don't work with it a long time. Have you found the solution?

**Comment by folkertvanheusden** [comment]
@BlackHoleVR try the latest version with my fix applied

@YandievRuslan there are still problems with the library. e.g. if the receive callback is too slow with copying the received data, then it can be overwritten by new data being received

**Comment by YandievRuslan** [comment]
@folkertvanheusden Hi! Thank you a lot, for prev pull request. Could you fix the problem with rewriting old data? I haven't work with hardware long time, and i don't have working LoRa setup to solve this issue. I guess to prevent overwriting data, we can each time allocate new memory for received data and save the reference to "modem->rx.data.buf". But then the callback should free the memory. It can cause memory leak. Or callback should first of all copy data from buffer using memcpy.
What do you think?

**Comment by YandievRuslan** [comment]
Thanks to @folkertvanheusden this issue is closed
