### ISSUE TITLE
doesn't receive on raspberry pi 3 and 4

### ISSUE THREAD

**Issue by folkertvanheusden** [YandievRuslan/sx1278-LoRa-RaspberryPi#8]
Hi,

I've tried several rpi 3s and 4s (with several tranceivers) but none of them seem to be able to receive packets.

Transmitting works, just not receiving.

Raspberry pi 1 and 2 work fine.

Any ideas?

**Comment by folkertvanheusden** [comment]
I dug further in it and saw that altough the modem sets the IRQ flag, the interrupt does not trigger.

e.g. this:

    lora_reg_read_byte(modem->spid, REG_IRQ_FLAGS) & IRQ_RXDONE 

returns 64 when it has received a packet.

Using gpioRead(17) in a loop I verified that the pin DOES go high when a packet is received.

**Comment by YandievRuslan** [comment]
Hi @folkertvanheusden ! Could you check this?

```
void lora_set_rxdone_dioISR(int gpio_n, rxDoneISR func, LoRa_ctl *modem){
	gpioSetMode(gpio_n, PI_INPUT);
	gpioSetISRFuncEx(gpio_n, RISING_EDGE, 0, func, (void *)modem);
}

void lora_set_txdone_dioISR(int gpio_n, txDoneISR func, LoRa_ctl *modem){
	gpioSetMode(gpio_n, PI_INPUT);
	gpioSetISRFuncEx(gpio_n, RISING_EDGE, 0, func, (void *)modem);
}
```

And exactly how works this function gpioSetISRFuncEx https://abyz.me.uk/rpi/pigpio/cif.html#gpioSetISRFuncEx ?

**Comment by YandievRuslan** [comment]
Maybe there is some changes in pigpio library and gpioSetISRFuncEx now works other way than used to. Because when i used this it worked fine on rpi3. Or maybe something changed on rpi3 software that causes gpioSetISRFuncEx behavior.

**Comment by folkertvanheusden** [comment]
Hi,

I'm digging further in it. And I found that the problem also occurs (in my setups that is) without the sx1278 library. E.g. when pulling a pin high/low manually.
See [pigpio](https://github.com/joan2937/pigpio/issues/542) and [kernel](https://github.com/raspberrypi/linux/issues/5159).

**Comment by folkertvanheusden** [comment]
@YandievRuslan something is peculiar with the signal-level of the dio0 pin.

If I reboot my rpi (2, 3 or 4 - doesn't matter) and then just let it sit idle and then transmit a packet from an other system, then DIO0 goes up to 3,28V as expected.

If I then start the receive_explicit example program, the voltage goes to 0.84V - as if the pull down resistor on the gpio pin (22) is removed.

Then I reboot the rpi, perform the same thing (sit idle, transmit a packet with other system) and then I run:
```
	int gpio_n = 22;
	gpioInitialise();

	// reset IRQ
	int spid = spiOpen(0, 32000, 0);
	lora_reg_write_byte(spid, REG_IRQ_FLAGS, 0xff);

	// wait for irq
	gpioSetMode(gpio_n, PI_INPUT);
	gpioSetISRFuncEx(gpio_n, EITHER_EDGE, 0, func, NULL);
```
then gpio 22 *does* go to 0V!

**Comment by folkertvanheusden** [comment]
It looks like that if I apply this patch:

```
 void lora_set_rxdone_dioISR(int gpio_n, rxDoneISR func, LoRa_ctl *modem){
        lora_reset_irq_flags(modem->spid);
        gpioSetMode(gpio_n, PI_INPUT);
        gpioSetISRFuncEx(gpio_n, RISING_EDGE, 0, func, (void *)modem);
 }
```

...that it works fine on at least the rpi3.

**Comment by YandievRuslan** [comment]
@folkertvanheusden could you test the pingpong example with this patch? If everything is ok, lets make a pull request.

**Comment by YandievRuslan** [comment]
@folkertvanheusden Hi!

**Comment by amir-sha** [comment]
I'm also unable to receive packets send from my ESP8266 with the same module on RPI3B+.

**Comment by folkertvanheusden** [comment]
@amir-sha can you try adding:

```
lora_reset_irq_flags(modem->spid);
```

at the top of **lora_set_rxdone_dioISR**

**Comment by amir-sha** [comment]
thanks for you answer ,I'm trying to use this library and read all the comments in this issue , Unfortunately the patch you proposed did not work.

**Comment by amir-sha** [comment]
I'm suspicious about this line : 
`modem.spiCS =0;//Raspberry SPI CE pin number`
pin number  or SPI channel ?! because when I change this line to 
`modem.spiCS =8;`
which is the real pin number , I get the following error 
```
2022-11-05 07:05:13 spiOpen: bad spiChan (8)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)
2022-11-05 07:05:13 spiXfer: bad handle (-76)

```
