### ISSUE TITLE
Problem with receiving data.

### ISSUE THREAD

**Issue by pyrotechnik** [YandievRuslan/sx1278-LoRa-RaspberryPi#9]
Hello, I have a problem receiving data on my raspberry pi zero. I accept the data, but it does not agree with what I sent at all. I had a simple test program done in python and the messages received agree here. So I don't know why I get absolutely random messages in my C program.
Thank you.

**Comment by YandievRuslan** [comment]
@pyrotechnik  Судя по нику ты говоришь по русски. Не совсем понимаю твой английский. Напиши на русском.

**Comment by pyrotechnik** [comment]
Я не из России, но надеюсь переводчик как-то понятно переведет.  У меня проблема с получением данных от модуля sx1278.  Я получаю данные, но они совсем не совпадают с тем, что я отправил.  Я сделал простую тестовую программу на питоне, и полученные здесь сообщения согласуются с тем, что я отправил.  Поэтому я не знаю, почему я получаю абсолютно случайные сообщения в своей программе на C.  И если я отправляю 2 одинаковых сообщения, программа каждый раз выводит другое.
  Спасибо.

**Comment by YandievRuslan** [comment]
Ты пробовал примеры из этой библиотеки? ping.c pong.c или другие?

**Comment by pyrotechnik** [comment]
нет, только rx_implicit.  Так что сегодня попробую другой.

**Comment by pyrotechnik** [comment]
Еще ничего. Я отправляю 16 байт данных с моего STM32. Но на малине в программе C я каждый раз получаю что-то другое. Я не знаю, может ли проблема быть в преобразовании в char. Мне было бы достаточно получить полученный дада в байтах. Но странно, что если я отправлю 2 одинаковых сообщения с неявным заголовком. Каждый раз получаю разный результат. Как я уже сказал в программе Python все работает корректно.

**Comment by YandievRuslan** [comment]
Не знаю даже, что посоветовать. Слишком мало вводных, не знаю, как и что ты делаешь и сам проверить не могу.
Я бы посоветовал слать данные в байтах и смотреть сами байты, а не char. Это же си, ты можешь любые данные в байтах посмотреть. Это работа с указателями

**Comment by pyrotechnik** [comment]
Вот код, который я пробую, я изменил payloadLen, preambleLen и GPIO. И я пытаюсь прочитать отдельные байты, используя rx->buf[x]. И с каждым полученным сообщением я получаю разные значения.

`#include "LoRa.h"

void * rx_f(void *p){
    rxData *rx = (rxData *)p;

    printf("rx done \n");
    printf("CRC error: %d\n", rx->CRC);
    printf("size: %u\n", rx->size);//Data we'v received
    printf("string: %x\n", rx->buf);//Data we'v received
    printf("string0: %x\n", rx->buf[0]);//Data we'v received
    printf("string1: %x\n", rx->buf[1]);//Data we'v received
    printf("string2: %x\n", rx->buf[2]);//Data we'v received
    printf("string3: %x\n", rx->buf[3]);//Data we'v received
    printf("string4: %d\n", rx->buf[4]);//Data we'v received
    printf("string5: %d\n", rx->buf[5]);//Data we'v received
    printf("string6: %d\n", rx->buf[6]);//Data we'v received
    printf("string7: %d\n", rx->buf[7]);//Data we'v received
    printf("string8: %d\n", rx->buf[8]);//Data we'v received
    printf("string9: %d\n", rx->buf[9]);//Data we'v received
    printf("string10: %d\n", (int)rx->buf[10]);//Data we'v received
    printf("string11: %d\n", (int)rx->buf[11]);//Data we'v received
    printf("string12: %d\n", (int)rx->buf[12]);//Data we'v received
    printf("string13: %d\n", (int)rx->buf[13]);//Data we'v received
    printf("string14: %d\n", (int)rx->buf[14]);//Data we'v received
    printf("string15: %d\n", (int)rx->buf[15]);//Data we'v received
    printf("RSSI: %d\n", rx->RSSI);
    printf("SNR: %f\n", rx->SNR);
    free(p);
    return NULL;
}

int main(){
    printf("Start");
    LoRa_ctl modem;

    //See for typedefs, enumerations and there values in LoRa.h header file
    modem.spiCS = 0;//Raspberry SPI CE pin number
    modem.rx.callback = rx_f;
    modem.eth.payloadLen = 16;//payload len used in implicit header mode
    modem.eth.preambleLen=0;
    modem.eth.bw = BW125;//Bandwidth 62.5KHz
    modem.eth.sf = SF7;//Spreading Factor 12
    modem.eth.ecr = CR8;//Error coding rate CR4/8
    modem.eth.CRC = 1;//Turn on CRC checking
    modem.eth.freq = 434500000;// 434.8MHz
    modem.eth.resetGpioN = 6;//GPIO4 on lora RESET pi
    modem.eth.dio0GpioN = 5;//GPIO17 on lora DIO0 pin to control Rxdone and Txdone interrupts
    modem.eth.outPower = OP20;//Output power
    modem.eth.powerOutPin = PA_BOOST;//Power Amplifire pin
    modem.eth.AGC = 1;//Auto Gain Control
    modem.eth.OCP = 240;// 45 to 240 mA. 0 to turn off protection
    modem.eth.implicitHeader = 1;//Implicit header mode
    modem.eth.syncWord = 0x12;
    //For detail information about SF, Error Coding Rate, Explicit header, Bandwidth, AGC, Over current protection and other features refer to sx127x>


    LoRa_begin(&modem);
    LoRa_receive(&modem);

    sleep(60);
    printf("end\n");
    LoRa_end(&modem);
}

`

**Comment by YandievRuslan** [comment]
@pyrotechnik решил проблему?
